<?php

namespace TomatoPHP\FilamentAlerts\Filament\Resources;

use Filament\Forms\Form;
use Filament\Infolists\Infolist;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables\Table;
use TomatoPHP\FilamentAlerts\Filament\Resources\NotificationsTemplateResource\Pages;
use TomatoPHP\FilamentAlerts\Models\NotificationsTemplate;

class NotificationsTemplateResource extends Resource
{
    use Translatable;

    protected static ?string $model = NotificationsTemplate::class;

    protected static ?string $navigationIcon = 'heroicon-o-bell';

    protected static ?int $navigationSort = 1;

    public static function shouldRegisterNavigation(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): string
    {
        return trans('filament-alerts::messages.group');
    }

    public static function getNavigationLabel(): string
    {
        return trans('filament-alerts::messages.templates.title');
    }

    public static function getTitle(): string
    {
        return trans('filament-alerts::messages.templates.title');
    }

    public static function getLabel(): ?string
    {
        return trans('filament-alerts::messages.templates.single');
    }

    public static function getPluralLabel(): ?string
    {
        return trans('filament-alerts::messages.templates.title');
    }

    public static function getTranslatableLocales(): array
    {
        return array_keys(filament('filament-alerts')->lang);
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return config('filament-alerts.resource.infolist.class')::make($infolist); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return config('filament-alerts.resource.form.class')::make($form);
    }

    public static function table(Table $table): Table
    {
        return config('filament-alerts.resource.table.class')::make($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListNotificationsTemplates::route('/'),
            'create' => Pages\CreateNotificationsTemplate::route('/create'),
            'edit' => Pages\EditNotificationsTemplate::route('/{record}/edit'),
            'view' => Pages\ViewNotificationsTemplates::route('/{record}'),
        ];
    }
}
