<?php

namespace TomatoPHP\FilamentAlerts\Tests;

use BladeUI\Heroicons\BladeHeroiconsServiceProvider;
use BladeUI\Icons\BladeIconsServiceProvider;
use Filament\Actions\ActionsServiceProvider;
use Filament\FilamentServiceProvider;
use Filament\Forms\FormsServiceProvider;
use Filament\Infolists\InfolistsServiceProvider;
use Filament\Notifications\NotificationsServiceProvider;
use Filament\Schemas\SchemasServiceProvider;
use Filament\Support\SupportServiceProvider;
use Filament\Tables\TablesServiceProvider;
use Filament\Widgets\WidgetsServiceProvider;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\LivewireServiceProvider;
use Orchestra\Testbench\Concerns\WithWorkbench;
use Orchestra\Testbench\TestCase as BaseTestCase;
use RyanChandler\BladeCaptureDirective\BladeCaptureDirectiveServiceProvider;
use Spatie\MediaLibrary\MediaLibraryServiceProvider;
use TomatoPHP\FilamentAlerts\Facades\FilamentAlerts;
use TomatoPHP\FilamentAlerts\FilamentAlertsServiceProvider;
use TomatoPHP\FilamentAlerts\Services\Concerns\NotificationDriver;
use TomatoPHP\FilamentAlerts\Services\Drivers\DatabaseDriver;
use TomatoPHP\FilamentAlerts\Services\Drivers\EmailDriver;
use TomatoPHP\FilamentAlerts\Tests\Models\User;

abstract class TestCase extends BaseTestCase
{
    use RefreshDatabase;
    use WithWorkbench;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        FilamentAlerts::register(
            [
                NotificationDriver::make('database')
                    ->label('Database')
                    ->color('primary')
                    ->icon('heroicon-o-server-stack')
                    ->driver(DatabaseDriver::class),
                NotificationDriver::make('email')
                    ->label('Email')
                    ->color('info')
                    ->icon('heroicon-o-envelope')
                    ->driver(EmailDriver::class),
            ]
        );
    }

    protected function defineDatabaseMigrations(): void
    {
        if (class_exists(\TomatoPHP\FilamentSettingsHub\FilamentSettingsHubServiceProvider::class)) {
            $this->loadMigrationsFrom(__DIR__ . '/../../vendor/tomatophp/filament-settings-hub/migrations');
        }
        $this->loadMigrationsFrom(__DIR__ . '/../../database/migrations');
    }

    protected function getPackageProviders($app): array
    {
        $providers = [
            ActionsServiceProvider::class,
            BladeCaptureDirectiveServiceProvider::class,
            BladeHeroiconsServiceProvider::class,
            BladeIconsServiceProvider::class,
            FilamentServiceProvider::class,
            FormsServiceProvider::class,
            InfolistsServiceProvider::class,
            LivewireServiceProvider::class,
            NotificationsServiceProvider::class,
            SchemasServiceProvider::class,
            SupportServiceProvider::class,
            TablesServiceProvider::class,
            WidgetsServiceProvider::class,
            MediaLibraryServiceProvider::class,
            FilamentAlertsServiceProvider::class,
            AdminPanelProvider::class,
        ];

        if (class_exists(\Spatie\LaravelSettings\LaravelSettingsServiceProvider::class)) {
            $providers[] = \Spatie\LaravelSettings\LaravelSettingsServiceProvider::class;
        }

        if (class_exists(\Filament\SpatieLaravelSettingsPluginServiceProvider::class)) {
            $providers[] = \Filament\SpatieLaravelSettingsPluginServiceProvider::class;
        }

        if (class_exists(\TomatoPHP\FilamentIcons\FilamentIconsServiceProvider::class)) {
            $providers[] = \TomatoPHP\FilamentIcons\FilamentIconsServiceProvider::class;
        }

        if (class_exists(\TomatoPHP\FilamentSettingsHub\FilamentSettingsHubServiceProvider::class)) {
            $providers[] = \TomatoPHP\FilamentSettingsHub\FilamentSettingsHubServiceProvider::class;
        }

        return $providers;
    }

    public function getEnvironmentSetUp($app): void
    {
        $app['config']->set('database.default', 'testing');
        $app['config']->set('auth.guards.testing.driver', 'session');
        $app['config']->set('auth.guards.testing.provider', 'testing');
        $app['config']->set('auth.providers.testing.driver', 'eloquent');
        $app['config']->set('auth.providers.testing.model', User::class);

        $app['config']->set('filament-translations.paths', [
            __DIR__ . '/../../vendor/orchestra/testbench-core/laravel',
        ]);

        if (class_exists(\TomatoPHP\FilamentIcons\FilamentIconsServiceProvider::class)) {
            $app['config']->set('filament-icons.cache', false);
        }
        $app['config']->set('queue.default', 'sync');
        $app['config']->set('filament-alerts.try.model', User::class);

        $app['config']->set('view.paths', [
            ...$app['config']->get('view.paths'),
            __DIR__ . '/../resources/views',
        ]);
    }
}
