<?php

namespace TomatoPHP\FilamentAlerts\Tests\Resources;

use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use TomatoPHP\FilamentAlerts\Filament\Actions\Table\NotificationAction;
use TomatoPHP\FilamentAlerts\Tests\Models\User;
use TomatoPHP\FilamentAlerts\Tests\Resources\UserResource\Pages\ListUsers;

class UserResource extends Resource
{
    protected static ?string $model = User::class;

    public static function form(Form $form): Form
    {
        return parent::form($form); // TODO: Change the autogenerated stub
    }

    public static function table(Table $table): Table
    {
        return $table->columns([
            TextColumn::make('id'),
        ])
            ->actions([
                NotificationAction::make(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListUsers::route('/'),
        ];
    }
}
